[dependencies]
rand = {package="rand", version="0.8.5", features=["small_rng"]}
ordered_float = {package="ordered-float", version="4.5.0"}

[package]
name = "utility"
version = "0.1.0"
edition = "2024"
